(() => {
  const list = () => document.querySelector('[data-users-list]');
  const msg = () => document.querySelector('[data-admin-message]');
  const esc = (v='') => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  function show(text,kind='ok'){const el=msg();if(!el)return;el.hidden=false;el.textContent=text;el.dataset.kind=kind;clearTimeout(show.t);show.t=setTimeout(()=>el.hidden=true,6000);}
  async function headers(){const user=window.KantiAuth?.user();if(!user)throw new Error('Du bisch nöd iigloggt.');const token=await user.jwt();return {'Authorization':`Bearer ${token}`,'Content-Type':'application/json'};}
  async function api(method='GET',body){const res=await fetch('/.netlify/functions/admin-users',{method,headers:await headers(),cache:'no-store',...(body?{body:JSON.stringify(body)}:{})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Fehler ${res.status}`);return data;}
  function render(users){const mount=list();if(!mount)return;if(!users.length){mount.innerHTML='<div class="empty-state">No kei Identity-Benutzer gfunde.</div>';return;}mount.innerHTML=users.map(u=>{const role=u.roles?.includes('admin')?'admin':'student',title=u.name||u.email||'Ohni Name';return `<div class="user-row" data-user-id="${esc(u.id)}"><div class="user-row-main"><span class="avatar">${esc((title[0]||'K').toUpperCase())}</span><span><strong>${esc(title)}</strong><small>${esc(u.email||'')}</small></span></div><div class="user-role-controls"><select class="select compact" data-role-select><option value="student" ${role==='student'?'selected':''}>student</option><option value="admin" ${role==='admin'?'selected':''}>admin</option></select><button class="btn btn-primary compact-btn" type="button" data-save-role>Speichere</button></div></div>`;}).join('');mount.querySelectorAll('[data-save-role]').forEach(btn=>btn.addEventListener('click',async()=>{const row=btn.closest('[data-user-id]'),role=row.querySelector('[data-role-select]').value;btn.disabled=true;btn.textContent='…';try{const data=await api('PATCH',{id:row.dataset.userId,role});show(`Rolle uf «${role}» gsetzt. ${data.note||''}`);}catch(e){show(e.message,'error');}finally{btn.disabled=false;btn.textContent='Speichere';}}));}
  async function load(){const mount=list();if(mount)mount.innerHTML='<div class="empty-state">Benutzer werde glade …</div>';try{const data=await api();render(data.users||[]);}catch(e){if(mount)mount.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`;show(e.message,'error');}}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelector('[data-users-reload]')?.addEventListener('click',load);window.addEventListener('kanti:auth',e=>{if(window.KantiAuth?.rolesOf(e.detail.user).includes('admin'))load();});setTimeout(()=>{if(window.KantiAuth?.roles().includes('admin'))load();},1200);});
})();
